import {
  BROWSER_CLICK_TOOL_NAME,
  BROWSER_GET_CONTENT_TOOL_NAME,
  BROWSER_NAVIGATE_TOOL_NAME,
  BROWSER_SCREENSHOT_TOOL_NAME,
  BROWSER_SCROLL_TOOL_NAME,
  BROWSER_SNAPSHOT_TOOL_NAME,
  BROWSER_TYPE_TOOL_NAME
} from './types'

const BROWSER_TOOL_NAMES = new Set<string>([
  BROWSER_NAVIGATE_TOOL_NAME,
  BROWSER_GET_CONTENT_TOOL_NAME,
  BROWSER_SCREENSHOT_TOOL_NAME,
  BROWSER_SNAPSHOT_TOOL_NAME,
  BROWSER_CLICK_TOOL_NAME,
  BROWSER_TYPE_TOOL_NAME,
  BROWSER_SCROLL_TOOL_NAME
])

export function isBrowserToolName(name: string): boolean {
  return BROWSER_TOOL_NAMES.has(name)
}
